import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";
import Header from "@/components/Header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Header />
        {children}
        <footer className="footer sm:footer-horizontal bg-[#F2F8F7] p-6 h-[344px] pt-20 justify-items-center">
          <aside className="">
            <Image
              aria-hidden
              src="/index/logo2.png"
              alt="Home"
              width={192}
              height={192}
              style={{
                width: '200px',
                height: '40px',
                objectFit: 'cover'
              }}
            />
            <p className="text-[#A5A5A5] mt-9 leading-7 w-[268px]">
              在快节奏里喘不过气？来 Time Zone
              <br />
              治愈岛屿！疲惫生活的加油站，为您
              <br />留住美好的时光与回忆～
            </p>
          </aside>
          <nav>
            <h6 className="footer-title text-[#000000]">blogs</h6>
            <a className="link link-hover text-[#555555] mt-2">旅行</a>
            <a className="link link-hover text-[#555555] mt-2">美食</a>
            <a className="link link-hover text-[#555555] mt-2">日常生活</a>
            <a className="link link-hover text-[#555555] mt-2">时尚</a>
            <a className="link link-hover text-[#555555] mt-2">商业</a>
          </nav>
          <nav>
            <h6 className="footer-title text-[#000000]">技术支持</h6>
            <a className="link link-hover text-[#555555] mt-2">FAQ</a>
            <a className="link link-hover text-[#555555] mt-2">技术支持</a>
            <a className="link link-hover text-[#555555] mt-2">Jobs</a>
            <a className="link link-hover text-[#555555] mt-2">隐私政策</a>
          </nav>
          <nav className="">
            <h6 className="footer-title text-[#000000]">意见反馈</h6>
            <div className="join mt-2 relative">
              <input type="text" className="border-none w-[438px] h-[52px] bg-[#DFF1F0] pl-4 !rounded-[6px] focus:border-[#00AAA1] resize-none focus:outline-none focus:ring-1 focus:ring-[#00AAA1]" placeholder="" />
              <span className="badge absolute right-1 top-[3.8px] badge-neutral bg-[#00AAA1] border-none badge-xs w-[100px] h-[45px] text-sm text-white">发送</span>
            </div>
            <h6 className="footer-title text-[#000000] mt-6">关注我们</h6>
            <div className="grid grid-cols-4 gap-4 mt-2">
              <Image
                aria-hidden
                src="/wx.svg"
                alt="Home"
                width={28}
                height={28}
                style={{
                  width: '28px',
                  height: '28px',
                  objectFit: 'cover'
                }}
              />
              <Image
                aria-hidden
                src="/wb.svg"
                alt="Home"
                width={28}
                height={28}
                style={{
                  width: '28px',
                  height: '28px',
                  objectFit: 'cover'
                }}
              />
              <Image
                aria-hidden
                src="/tt.svg"
                alt="Home"
                width={28}
                height={28}
                style={{
                  width: '28px',
                  height: '28px',
                  objectFit: 'cover'
                }}
              />
              <Image
                aria-hidden
                src="/fb.svg"
                alt="Home"
                width={28}
                height={28}
                style={{
                  width: '28px',
                  height: '28px',
                  objectFit: 'cover'
                }}
              />
            </div>
          </nav>
        </footer>
      </body>
    </html>
  );
}
